# This tells Render how to build and start the app
build:
  - npm install

# Start the app
start: node server.js

# Environment variables for the deployed site
env:
  - name: PUBLIC_URL
    value: "https://trash-to-treasure.onrender.com"

# Health check (Render will attempt this endpoint to verify the service)
health_check_path: /health